Repository codestates-seb/seb42_main_019, pull requests merged in 2023-03, with the labels that each got.

#8 [design]header edit
  FE/front/src/App.js
  FE/front/src/components/common/Footer.module.css
  FE/front/src/components/common/Header.module.css
  FE/front/src/components/common/Header2.js
  FE/front/src/components/common/Pagenation.module.css
  FE/front/src/index.css
  FE/front/src/style/CommonStyle.css
Labels: design

#14 Design/fe headers
  FE/front/package-lock.json
  FE/front/package.json
  FE/front/src/App.js
  FE/front/src/App.module.css
  FE/front/src/components/JSB/Alert/AlertList.js
  FE/front/src/components/JSB/Alert/AlertList.module.css
  FE/front/src/components/JSB/Alert/AlertListMS.js
  FE/front/src/components/JSB/Alert/AlertListMs.module.css
  FE/front/src/components/JSB/HomeSearch.js
  FE/front/src/components/JSB/HomeSearch.module.css
  FE/front/src/components/JSB/message/Mcontent.js
  FE/front/src/components/JSB/message/Mcontent.module.css
  FE/front/src/components/JSB/message/MessageList1.js
  FE/front/src/components/JSB/message/MessageList1.module.css
  FE/front/src/components/JSB/message/MessageList2.js
  FE/front/src/components/JSB/message/MessageList2.module.css
  FE/front/src/components/common/BookList.module.css
  FE/front/src/components/common/Footer.module.css
  FE/front/src/components/common/Header.js
  FE/front/src/components/common/Header.module.css
  FE/front/src/components/common/Header2.js
  FE/front/src/index.css
  FE/front/src/pages/SB/Alert.js
  FE/front/src/pages/SB/Alert.module.css
  FE/front/src/pages/SB/Home.js
  FE/front/src/pages/SB/Home.module.css
  FE/front/src/pages/SB/MessageList.module.css
  FE/front/src/pages/SB/MessageView.js
  FE/front/src/pages/SB/MessageView.module.css
  FE/front/src/pages/SB/MessageWrite.js
  FE/front/src/pages/SB/MessageWrite.module.css
  FE/front/src/style/CommonStyle.css
Labels: 조수빈, design

#17 [design]mypage
  FE/front/src/App.js
  FE/front/src/assets/adimg.png
  FE/front/src/components/JSB/message/MessageList1.js
  FE/front/src/components/JSB/message/MessageList1.module.css
  FE/front/src/components/common/Footer.module.css
  FE/front/src/components/common/Header.js
  FE/front/src/components/common/Header.module.css
  FE/front/src/components/common/Header2.js
  FE/front/src/components/common/Header2.module.css
  FE/front/src/pages/SB/Home.js
  FE/front/src/pages/SB/MessageView.module.css
  FE/front/src/pages/SB/MessageWrite.module.css
  FE/front/src/pages/SB/Mypage.js
  FE/front/src/pages/SB/Mypage.module.css
  FE/front/src/style/CommonStyle.css
Labels: 조수빈, design

#25 [design]page complete
  FE/front/src/App.js
  FE/front/src/assets/bookshelf.png
  FE/front/src/assets/bookshelf2.png
  FE/front/src/assets/tradebook.png
  FE/front/src/components/JSB/BookShelf/BSlist.js
  FE/front/src/components/JSB/BookShelf/BSlist.module.css
  FE/front/src/components/JSB/Search.js
  FE/front/src/components/JSB/Search.module.css
  FE/front/src/components/JSB/message/MessageList3.js
  FE/front/src/components/JSB/message/MessageList3.module.css
  FE/front/src/components/common/Nav.js
  FE/front/src/dummyData/SB/bookData.jsx
  FE/front/src/dummyData/SB/messageContent1.jsx
  FE/front/src/pages/SB/Home.js
  FE/front/src/pages/SB/Home.module.css
  FE/front/src/pages/SB/MyBookShelf.js
  FE/front/src/pages/SB/MyBookShelf.module.css
  FE/front/src/pages/SB/Mypage.js
  FE/front/src/pages/SB/Mypage.module.css
  FE/front/src/pages/SB/TradeBookList.js
  FE/front/src/pages/SB/TradeBookList.module.css
  FE/front/src/style/CommonStyle.css
Labels: 조수빈, design

#29 Design/fe headers
  FE/front/src/App.js
  FE/front/src/assets/jonghyun2.jpeg
  FE/front/src/assets/key.jpg
  FE/front/src/assets/minho.jpg
  FE/front/src/assets/onyou.jpeg
  FE/front/src/assets/taemin.jpg
  FE/front/src/components/JSB/Alert/AlertListMS.js
  FE/front/src/components/JSB/Alert/AlertListMs.module.css
  FE/front/src/components/JSB/Alert/MapAlert.js
  FE/front/src/components/JSB/Alert/MapAlert.module.css
  FE/front/src/components/JSB/Alert/[x]AlertList.js
  FE/front/src/components/JSB/Alert/[x]AlertList.module.css
  FE/front/src/components/JSB/BookShelf/BS.js
  FE/front/src/components/JSB/BookShelf/BSlist.module.css
  FE/front/src/components/JSB/message/Avatar.js
  FE/front/src/components/JSB/message/Avatar.module.css
  FE/front/src/components/JSB/message/MessageList1.js
  FE/front/src/components/JSB/message/MessageList1.module.css
  FE/front/src/components/JSB/message/MessageList2.module.css
  FE/front/src/components/JSB/message/MessageList3.js
  FE/front/src/components/common/Book.js
  FE/front/src/components/common/BookList.js
  FE/front/src/components/common/BookList.module.css
  FE/front/src/dummyData/SB/messageContent1.jsx
  FE/front/src/pages/SB/Alert.js
  FE/front/src/pages/SB/Home.js
  FE/front/src/pages/SB/Home.module.css
  FE/front/src/pages/SB/MessageList01.module.css
  FE/front/src/pages/SB/MessageList02.js
  FE/front/src/pages/SB/MessageView.js
  FE/front/src/pages/SB/MessageWrite.js
  FE/front/src/pages/SB/MyBookShelf.js
  FE/front/src/pages/SB/Mypage.js
  FE/front/src/pages/SB/[x]MessageList01.js
  FE/front/src/pages/SB/[x]MessageList01.module.css
Labels: 조수빈, design

#33 [design]detail화면 수정
  FE/front/src/App.js
  FE/front/src/pages/JH/CustomerDetailView.js
  FE/front/src/pages/JH/CustomerDetailView.module.css
  FE/front/src/pages/JH/SellerDetailView.js
  FE/front/src/pages/JH/SellerDetailViewEdit.js
  FE/front/src/pages/JH/SellerDetailViewEdit.module.css
Labels: design

#39 [design]1차 css완성
  FE/front/src/App.js
  FE/front/src/App.module.css
  FE/front/src/assets/404.svg
  FE/front/src/assets/question.svg
  FE/front/src/components/KHJ/BookInfo.js
  FE/front/src/components/KHJ/ModalPopUp.module.css
  FE/front/src/components/common/Background.module.css
  FE/front/src/pages/HJ/404.js
  FE/front/src/pages/HJ/HJpage.module.css
  FE/front/src/pages/HJ/M_BookInfo.js
  FE/front/src/pages/HJ/M_CommentCreate.js
  FE/front/src/pages/HJ/M_UserComment.js
  FE/front/src/pages/HJ/Missing.js
  FE/front/src/style/CommonStyle.css
Labels: design

#41 [feat]로그인 폼 저장 및 핸들러추가
  FE/front/src/pages/JH/Login.js
  FE/front/src/pages/JH/Login.module.css
Labels: feat

#44 [feat]delete
  FE/front/src/App.js
  FE/front/src/components/JSB/Alert/MapAlert.module.css
  FE/front/src/components/JSB/Alert/MapAlertMini.js
  FE/front/src/components/JSB/Alert/[x]MapAlert.js
  FE/front/src/components/JSB/message/Message4.js
  FE/front/src/components/JSB/message/MessageList1.js
  FE/front/src/components/JSB/message/MessageList1.module.css
  FE/front/src/components/JSB/message/MessageList3.js
  FE/front/src/components/JSB/message/MessageList3.module.css
  FE/front/src/components/common/BookList.module.css
  FE/front/src/dummyData/SB/messageContent1.js
  FE/front/src/pages/SB/Alert.js
  FE/front/src/pages/SB/Alert.module.css
  FE/front/src/pages/SB/MessageList02.js
  FE/front/src/pages/SB/MessageList02.module.css
  FE/front/src/pages/SB/MessageView.js
Labels: 조수빈, feat

#50 [feat] Book Read feature add
  BE/src/main/java/izone/izoneProject/book/controller/BookController.java
  BE/src/main/java/izone/izoneProject/book/dto/BookPostDto.java
  BE/src/main/java/izone/izoneProject/book/dto/BookResponseDto.java
  BE/src/main/java/izone/izoneProject/book/mapper/BookMapper.java
  BE/src/main/java/izone/izoneProject/book/repository/BookRepository.java
  BE/src/main/java/izone/izoneProject/book/service/BookService.java
Labels: 안병옥, feat

#52 [feat] book & user like&dislike impl
  BE/src/main/java/izone/izoneProject/book/controller/BookController.java
  BE/src/main/java/izone/izoneProject/book/dto/BookDislikeResponseDto.java
  BE/src/main/java/izone/izoneProject/book/dto/BookLikeResponseDto.java
  BE/src/main/java/izone/izoneProject/book/dto/BookResponseDto.java
  BE/src/main/java/izone/izoneProject/book/entity/Book.java
  BE/src/main/java/izone/izoneProject/book/entity/BookLike.java
  BE/src/main/java/izone/izoneProject/book/mapper/BookMapper.java
  BE/src/main/java/izone/izoneProject/book/repository/BookLikeRepository.java
  BE/src/main/java/izone/izoneProject/book/service/BookCommentService.java
  BE/src/main/java/izone/izoneProject/book/service/BookLikeService.java
  BE/src/main/java/izone/izoneProject/book/service/BookService.java
  BE/src/main/java/izone/izoneProject/common/enums/LikeStatus.java
  BE/src/main/java/izone/izoneProject/common/exception/BusinessLogicException.java
  BE/src/main/java/izone/izoneProject/common/exception/ExceptionCode.java
  BE/src/main/java/izone/izoneProject/user/controller/UserController.java
  BE/src/main/java/izone/izoneProject/user/dto/UserDto.java
  BE/src/main/java/izone/izoneProject/user/entity/User.java
  BE/src/main/java/izone/izoneProject/user/entity/UserDislike.java
  BE/src/main/java/izone/izoneProject/user/entity/UserLike.java
  BE/src/main/java/izone/izoneProject/user/mapper/UserMapper.java
  BE/src/main/java/izone/izoneProject/user/repository/UserLikeRepository.java
  BE/src/main/java/izone/izoneProject/user/repository/UserRepository.java
  BE/src/main/java/izone/izoneProject/user/service/UserService.java
Labels: 안병옥, feat

#54 [feat] book totalLikeCount & DislikeCount impl
  BE/src/main/java/izone/izoneProject/book/controller/BookController.java
  BE/src/main/java/izone/izoneProject/book/dto/BookResponseDto.java
  BE/src/main/java/izone/izoneProject/book/entity/Book.java
  BE/src/main/java/izone/izoneProject/book/entity/BookComment.java
  BE/src/main/java/izone/izoneProject/book/repository/BookRepository.java
  BE/src/main/java/izone/izoneProject/book/service/BookCommentService.java
  BE/src/main/java/izone/izoneProject/book/service/BookLikeService.java
  BE/src/main/java/izone/izoneProject/book/service/BookService.java
Labels: docs, 안병옥

#56 [docs] totalBookComments
  BE/src/main/java/izone/izoneProject/book/entity/BookComment.java
  BE/src/main/java/izone/izoneProject/book/repository/BookCommentRepository.java
  BE/src/main/java/izone/izoneProject/book/repository/BookRepository.java
  BE/src/main/java/izone/izoneProject/book/service/BookCommentService.java
  BE/src/main/java/izone/izoneProject/book/service/BookService.java
Labels: docs, 안병옥

#57 [fix] book entity import add
  BE/src/main/java/izone/izoneProject/book/entity/Book.java
Labels: 안병옥, fix

#60 [feat] user BookList & message ReadAt
  BE/src/main/java/izone/izoneProject/book/controller/BookController.java
  BE/src/main/java/izone/izoneProject/book/repository/BookRepository.java
  BE/src/main/java/izone/izoneProject/book/service/BookService.java
  BE/src/main/java/izone/izoneProject/message/entity/Message.java
Labels: 안병옥, feat

#61 [docs] add 'server.servlet.encoding.charset' to application.yml
  BE/src/main/resources/application.yml
Labels: docs, 안병옥

#62 [docs] setAllowCredentials(true) modified)
  BE/src/main/java/izone/izoneProject/security/config/SecurityConfiguration.java
Labels: docs, 안병옥

#64 Feat/fe 검색구현실패
  FE/front/src/App.js
  FE/front/src/components/JSB/BookShelf/BSlist.module.css
  FE/front/src/components/JSB/Search.js
  FE/front/src/components/KHJ/BS.js
  FE/front/src/components/KHJ/BSlist.module.css
  FE/front/src/components/KHJ/BookInfo.js
  FE/front/src/components/KHJ/DropdownOpt.js
  FE/front/src/components/KHJ/ModalPopTrade.js
  FE/front/src/components/KHJ/ModalPopUp.module.css
  FE/front/src/components/KHJ/Rate.js
  FE/front/src/components/KHJ/atom.js
  FE/front/src/dummyData/ratedata.js
  FE/front/src/dummyData/tradeShelfdata.js
  FE/front/src/pages/HJ/BookSearch.js
  FE/front/src/pages/HJ/BookSearchResult.js
  FE/front/src/pages/HJ/HJpage.module.css
  FE/front/src/pages/HJ/Missing.js
Labels: bug, 김현지

#69 [docs] post book decoed UTF8 & readAt security
  BE/src/main/java/izone/izoneProject/book/controller/BookController.java
  BE/src/main/java/izone/izoneProject/book/entity/Book.java
  BE/src/main/java/izone/izoneProject/message/controller/MessageController.java
  BE/src/main/java/izone/izoneProject/message/entity/Message.java
  BE/src/main/java/izone/izoneProject/message/repository/MessageRepository.java
  BE/src/main/java/izone/izoneProject/message/service/MessageService.java
  BE/src/main/java/izone/izoneProject/security/config/SecurityConfiguration.java
Labels: docs, 안병옥

#70 [test]file
  FE/front/package-lock.json
  FE/front/package.json
  FE/front/src/App.js
  FE/front/src/App.module.css
  FE/front/src/States/LoginState.js
  FE/front/src/components/JSB/message/MessageList1.js
  FE/front/src/components/common/Footer.module.css
  FE/front/src/pages/JH/Login.js
  FE/front/src/pages/SB/MyBookShelf.js
  FE/front/src/pages/SB/Mypage.js
  FE/front/src/pages/SB/Mypage.module.css
  FE/front/src/pages/SB/TradeBookList.js
  FE/front/src/pages/SB/TradeBookList.module.css
  FE/front/src/pages/SB/[x] test.js
  FE/front/src/pages/SB/[x] text.js
  FE/front/src/pages/SB/[x]MessageList01.js
  FE/front/src/pages/SB/[x]MessageList01.module.css
Labels: 조수빈, test

#72 [docs] otherUserBookList Get & application-dev.yml add
  BE/src/main/java/izone/izoneProject/book/controller/BookController.java
  BE/src/main/java/izone/izoneProject/book/service/BookService.java
  BE/src/main/resources/application-dev.yml
  BE/src/main/resources/application.yml
Labels: docs, 안병옥

#77 [feat]login
  FE/front/src/App.js
  FE/front/src/States/PrivateRoutes.js
  FE/front/src/components/common/Header.js
  FE/front/src/components/common/LogoutBtn.js
  FE/front/src/components/common/Nav.js
  FE/front/src/components/common/isLogin.js
  FE/front/src/pages/SB/Alert.js
  FE/front/src/pages/SB/Home.js
  FE/front/src/pages/SB/MyPage.js
  FE/front/src/pages/SB/ReveivedMessages.js
Labels: 조수빈, feat

#78 [Feat/FE] 로그인 구현, 검색페이지 오류 수정, 책 등록 상세페이지 이동 구현
  FE/front/src/App.js
  FE/front/src/components/JSB/Search.js
  FE/front/src/components/KHJ/BS.js
  FE/front/src/components/KHJ/BookInfo.js
  FE/front/src/components/KHJ/BookInfo.module.css
  FE/front/src/components/common/Footer.module.css
  FE/front/src/components/common/Nav.js
  FE/front/src/dummyData/bookinfo.js
  FE/front/src/pages/HJ/BookSearch.js
  FE/front/src/pages/HJ/BookSearchResult.js
  FE/front/src/pages/HJ/atom.js
  FE/front/src/pages/JH/CustomerDetailView.js
  FE/front/src/pages/SB/Home.js
Labels: 김현지, feat

#80 [fix] application-*.yml modified & build.gradel mysql add
  BE/build.gradle
  BE/src/main/resources/application-dev.yml
  BE/src/main/resources/application-release.yml
Labels: 안병옥, fix

#86 [fix] release.yml & commnet patch & user get
  BE/build.gradle
  BE/src/main/java/izone/izoneProject/book/controller/BookCommentController.java
  BE/src/main/java/izone/izoneProject/book/controller/BookController.java
  BE/src/main/java/izone/izoneProject/book/dto/BookPatchDto.java
  BE/src/main/java/izone/izoneProject/book/dto/BookPostDto.java
  BE/src/main/java/izone/izoneProject/book/dto/BookResponseDto.java
  BE/src/main/java/izone/izoneProject/book/entity/Book.java
  BE/src/main/java/izone/izoneProject/book/service/BookCommentService.java
  BE/src/main/java/izone/izoneProject/book/service/BookService.java
  BE/src/main/java/izone/izoneProject/message/service/MessageService.java
  BE/src/main/java/izone/izoneProject/user/controller/UserController.java
  BE/src/main/java/izone/izoneProject/user/dto/UserCommentDto.java
  BE/src/main/java/izone/izoneProject/user/service/UserService.java
  BE/src/main/resources/application-dev.yml
  BE/src/main/resources/application-release.yml
  BE/src/main/resources/application.yml
Labels: 안병옥, fix

#88 [feat]use
  FE/front/src/pages/SB/Alert.js
Labels: 조수빈, feat

#90 [feat]책등록페이지 구현
  FE/front/src/App.js
  FE/front/src/pages/JH/CreateBook.js
  FE/front/src/pages/JH/CreateBook.module.css
  FE/front/src/pages/JH/Login.js
Labels: feat

#95 [fix] user delete - cascade
  BE/src/main/java/izone/izoneProject/message/entity/Message.java
  BE/src/main/java/izone/izoneProject/user/entity/User.java
  BE/src/main/java/izone/izoneProject/user/service/UserService.java
Labels: 안병옥, fix

#97 [Feat/FE] 북커멘트 완료, 유저 커멘트CR완료, 유저 라이크 완료
  FE/front/src/components/KHJ/Comment.js
  FE/front/src/components/KHJ/CreateBookComment.js
  FE/front/src/components/KHJ/ModalPopCreate.js
  FE/front/src/components/KHJ/ModalPopUp.module.css
  FE/front/src/components/KHJ/Profile.js
  FE/front/src/components/KHJ/Profile.module.css
  FE/front/src/components/KHJ/Rate.js
  FE/front/src/components/common/LogoutBtn.js
  FE/front/src/pages/HJ/BookSearchResult.module.css
  FE/front/src/pages/HJ/M_CommentCreate.js
  FE/front/src/pages/HJ/UserRateList.css
  FE/front/src/pages/HJ/UserRateList.js
  FE/front/src/pages/JH/CustomerDetailView.module.css
  FE/front/src/pages/JH/Login.js
  FE/front/src/pages/JH/SellerDetailView.js
Labels: bug, 김현지, feat

#111 [fix] secrurityConfigurer add PUT
  BE/src/main/java/izone/izoneProject/security/config/SecurityConfiguration.java
  FE/front/src/components/common/Nav.js
  FE/front/src/components/common/Nav.module.css
  FE/front/src/pages/SB/Alert.js
Labels: 안병옥, fix
