Repository codestates-seb/seb42_main_019, pull requests merged in 2023-04, with the labels that each got.

#135 [feat]messages
  FE/front/src/App.js
  FE/front/src/api/api.js
  FE/front/src/pages/JH/CustomerDetailView.js
  FE/front/src/pages/SB/MessageReceive.js
  FE/front/src/pages/SB/MessageSend.js
  FE/front/src/pages/SB/TradeMessage.js
Labels: 조수빈, feat

#141 [fix] int exchange
  BE/src/main/java/izone/izoneProject/book/dto/BookPatchDto.java
  BE/src/main/java/izone/izoneProject/book/dto/BookPostDto.java
  BE/src/main/java/izone/izoneProject/book/dto/BookResponseDto.java
  BE/src/main/java/izone/izoneProject/book/entity/Book.java
Labels: 안병옥, fix

#142 [feat]detail수정,[design]로그인,회원가입 수정
  FE/front/src/pages/JH/CustomerDetailView.js
  FE/front/src/pages/JH/Login.module.css
  FE/front/src/pages/JH/SellerDetailView.js
  FE/front/src/pages/JH/SellerDetailViewEdit.js
  FE/front/src/pages/JH/SignUp.module.css
Labels: feat, design

#145 [feat]edit페이지 구현완료
  FE/front/src/pages/JH/SellerDetailViewEdit.js
Labels: 임지현, feat
